//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveFullLife.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place_information
    {
        public int Id_place { get; set; }
        public string Place_discriptin { get; set; }
        public byte[] Photo_place { get; set; }
    
        public virtual Place Place { get; set; }
    }
}
