//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveFullLife.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_information
    {
        public int Id_user { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
    
        public virtual User User { get; set; }
        public virtual Users_adress Users_adress { get; set; }
    }
}
