//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveFullLife.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_adress
    {
        public int Id_adress { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<int> House { get; set; }
        public Nullable<int> Flat { get; set; }
    
        public virtual Users_information Users_information { get; set; }
    }
}
