//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveFullLife.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visited_places
    {
        public int Id { get; set; }
        public Nullable<int> Visited_place_id { get; set; }
        public Nullable<int> V_User_id { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual User User { get; set; }
    }
}
